local harpoon = require("harpoon")

harpoon:setup()

vim.keymap.set("n", "<leader>a", function()
  harpoon:list():add()
end)
vim.keymap.set("n", "<leader>e", function()
  harpoon.ui:toggle_quick_menu(harpoon:list())
end)

vim.keymap.set("n", "<leader>j", function()
  harpoon:list():select(1)
end)
vim.keymap.set("n", "<leader>k", function()
  harpoon:list():select(2)
end)
vim.keymap.set("n", "<leader>l", function()
  harpoon:list():select(3)
end)
vim.keymap.set("n", "<leader>;", function()
  harpoon:list():select(4)
end)
vim.keymap.set("n", "<leader>J", function()
  harpoon:list():replace_at(1)
end)
vim.keymap.set("n", "<leader>K", function()
  harpoon:list():replace_at(2)
end)
vim.keymap.set("n", "<leader>L", function()
  harpoon:list():replace_at(3)
end)
vim.keymap.set("n", "<leader>:", function()
  harpoon:list():replace_at(4)
end)
